/**
 * MojoELF; load ELF binaries from a memory buffer.
 *
 * Please see the file LICENSE.txt in the source's root directory.
 *
 *  This file was autogenerated from dumpx11fn.pl. Do not edit by hand!
 */

// Do not #pragma once this file, it's intentionally included multiple times.

MACTRAMPOLINE(int,XMissingExtension,(Display* a,_Xconst char* b),(a,b),return)
MACTRAMPOLINE(XExtensionInfo*,XextCreateExtension,(void),(),return)
MACTRAMPOLINE(void,XextDestroyExtension,(XExtensionInfo* a),(a),)
MACTRAMPOLINE(XExtDisplayInfo*,XextAddDisplay,(XExtensionInfo* a,Display* b,_Xconst char* c,XExtensionHooks* d,int e,XPointer f),(a,b,c,d,e,f),return)
MACTRAMPOLINE(int,XextRemoveDisplay,(XExtensionInfo* a,Display* b),(a,b),return)
MACTRAMPOLINE(XExtDisplayInfo*,XextFindDisplay,(XExtensionInfo* a,Display* b),(a,b),return)
MACTRAMPOLINE(Bool,XShmQueryExtension,(Display* a),(a),return)
MACTRAMPOLINE(int,XShmGetEventBase,(Display* a),(a),return)
MACTRAMPOLINE(Bool,XShmQueryVersion,(Display* a,int* b,int* c,Bool* d),(a,b,c,d),return)
MACTRAMPOLINE(int,XShmPixmapFormat,(Display* a),(a),return)
MACTRAMPOLINE(Bool,XShmAttach,(Display* a,XShmSegmentInfo* b),(a,b),return)
MACTRAMPOLINE(Bool,XShmDetach,(Display* a,XShmSegmentInfo* b),(a,b),return)
MACTRAMPOLINE(Bool,XShmPutImage,(Display* a,Drawable b,GC c,XImage* d,int e,int f,int g,int h,unsigned i,unsigned j,Bool k),(a,b,c,d,e,f,g,h,i,j,k),return)
MACTRAMPOLINE(Bool,XShmGetImage,(Display* a,Drawable b,XImage* c,int d,int e,unsigned f),(a,b,c,d,e,f),return)
MACTRAMPOLINE(XImage*,XShmCreateImage,(Display* a,Visual* b,unsigned c,int d,char* e,XShmSegmentInfo* f,unsigned g,unsigned h),(a,b,c,d,e,f,g,h),return)
MACTRAMPOLINE(Pixmap,XShmCreatePixmap,(Display* a,Drawable b,char* c,XShmSegmentInfo* d,unsigned e,unsigned f,unsigned g),(a,b,c,d,e,f,g),return)

// end of mactrampolines_xext.h ...

